fix: music player specific-song command crashes by handling missing song titles during library load and title search.
System.NullReferenceException: Object reference not set to an instance of an object.
   at MixItUp.WPF.Services.WindowsMusicPlayerService.<>c__DisplayClass30_0.<SearchAndPlaySong>b__0(MusicPlayerSong s) in D:\CODE\com.mixitupapp\Desktop\MixItUp.WPF\Services\WindowsMusicPlayerService.cs:line 374
   at System.Linq.Enumerable.WhereEnumerableIterator`1.GetCount(Boolean onlyIfCheap)
   at MixItUp.WPF.Services.WindowsMusicPlayerService.SearchAndPlaySong(String searchText, Boolean stopOnCompletion) in D:\CODE\com.mixitupapp\Desktop\MixItUp.WPF\Services\WindowsMusicPlayerService.cs:line 375
   at MixItUp.Base.Model.Actions.MusicPlayerActionModel.PerformInternal(CommandParametersModel parameters) in D:\CODE\com.mixitupapp\Desktop\MixItUp.Base\Model\Actions\MusicPlayerActionModel.cs:line 70
   at MixItUp.Base.Model.Actions.ActionModelBase.Perform(CommandParametersModel parameters) in D:\CODE\com.mixitupapp\Desktop\MixItUp.Base\Model\Actions\ActionModelBase.cs:line 106
   at MixItUp.Base.Services.CommandService.RunDirectlyInternal(CommandInstanceModel commandInstance, CommandParametersModel parameters) in D:\CODE\com.mixitupapp\Desktop\MixItUp.Base\Services\CommandService.cs:line 620
   at MixItUp.Base.Services.CommandService.RunDirectly(CommandInstanceModel commandInstance) in D:\CODE\com.mixitupapp\Desktop\MixItUp.Base\Services\CommandService.cs:line 320
Full Stack:   at System.Environment.get_StackTrace()
   at MixItUp.Base.Util.Logger.Log(LogLevel level, Exception ex, Boolean includeStackTrace) in D:\CODE\com.mixitupapp\Desktop\MixItUp.Base\Util\Logger.cs:line 136
   at MixItUp.Base.Util.Logger.Log(Exception ex, Boolean includeStackTrace) in D:\CODE\com.mixitupapp\Desktop\MixItUp.Base\Util\Logger.cs:line 122
   at MixItUp.Base.Services.CommandService.RunDirectly(CommandInstanceModel commandInstance) in D:\CODE\com.mixitupapp\Desktop\MixItUp.Base\Services\CommandService.cs:line 320
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at MixItUp.Base.Services.CommandService.RunDirectly(CommandInstanceModel commandInstance)
   at MixItUp.Base.Services.CommandService.BackgroundCommandTypeRunner(CommandTypeEnum type) in D:\CODE\com.mixitupapp\Desktop\MixItUp.Base\Services\CommandService.cs:line 571
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecuteFromThreadPool(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()