fix: Webhook command crash when using duplicate json pairs
CRASHING EXCEPTION:
System.ArgumentException: An item with the same key has already been added. Key: test
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](List`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at MixItUp.Base.Model.Commands.WebhookCommandModel.GetTestSpecialIdentifiers() in C:\Users\admin\source\repos\mixitupapp\Desktop\MixItUp.Base\Model\Commands\WebhookCommandModel.cs:line 31
   at MixItUp.Base.ViewModel.Commands.CommandEditorWindowViewModelBase.TestCommandWithTestCommandParameters(CommandModelBase command) in C:\Users\admin\source\repos\mixitupapp\Desktop\MixItUp.Base\ViewModel\Commands\CommandEditorWindowViewModelBase.cs:line 57
   at MixItUp.WPF.Controls.Commands.CommandListingButtonsControl.PlayButton_Click(Object sender, RoutedEventArgs e) in C:\Users\admin\source\repos\mixitupapp\Desktop\MixItUp.WPF\Controls\Commands\CommandListingButtonsControl.xaml.cs:line 159
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Environment.get_StackTrace()
   at MixItUp.WPF.App.HandleCrash(Exception ex) in C:\Users\admin\source\repos\mixitupapp\Desktop\MixItUp.WPF\App.xaml.cs:line 171
   at MixItUp.WPF.App.Current_DispatcherUnhandledException(Object sender, DispatcherUnhandledExceptionEventArgs e) in C:\Users\admin\source\repos\mixitupapp\Desktop\MixItUp.WPF\App.xaml.cs:line 141
   at System.Windows.Threading.Dispatcher.CatchException(Exception e)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at MixItUp.WPF.Program.Main(String[] args) in C:\Users\admin\source\repos\mixitupapp\Desktop\MixItUp.WPF\Program.cs:line 24