Fix NullReferenceException in Lumia Stream action when API settings options are missing
CRASHING EXCEPTION:
System.NullReferenceException: Object reference not set to an instance of an object.
   at MixItUp.Base.ViewModel.Actions.LumiaStreamActionEditorControlViewModel.OnOpenInternal() in D:\CODE\com.mixitupapp\Desktop\MixItUp.Base\ViewModel\Actions\LumiaStreamActionEditorControlViewModel.cs:line 196