feat/dotnet-9-migration_material-design-3-refresh (#292)
* part 1 migration update

* update material design library to version 5

* remove secondary color to make it use default accent

* Revert "remove secondary color to make it use default accent"

This reverts commit 0cf04d43a163f05056d6dbb4fd7dd7dec8d644c2.

* fix botaccount binding case sensitive in streamingplatformaccount control

* make the login page cute

* adjust main menu theme colors + rounded corners W

* change elevation value for dialoghost common style

* change .csproj to project sdk style targeting net8.0-windows

* Update MixItUp.Reporter to .net8

* update base .csproj to .net8, bump System.IO.Ports to v8

* replace assembly=mscorlib with assembly=System.Runtime  (xmlns:system="clr-namespace:System;assembly=System.Runtime")

* bump up deprecated and vulnerable libraries, and remove any old/unused ones

* fix developer api

* update assemblyinfo.cs to hide warning CA1416

* update WindowsFileService.cs to reuse httpclient and also updated deprecated WebClient to HttpClient

* updated WindowsInputService - PermissionSetAttribute' is obsolete and use IntPtr.Zero instead of !null

* update WindowsOBSService authentication method  - 'SHA256Managed' is obsolete

* update WindowsTelemetryService -   'TelemetryClient.TelemetryClient()' is obsolete

* disable nullable errors for now from base proj

* DonorDrive service fix

* Updating hypetrain twitch eventsub from v1 to v2 due to deprecation.

* Fix healing logic for stream boss overlay widget

* Added auto reconnect logic for twitch client (eventsub)

* Fix missing twitch classification labels in twitch action

* Added support for voicemod v3

* Refresh oauth page and give it a new look

* fix race condition between the "Save" operation and the "RefreshWidgetPreview" (triggered by the refresh timer or property changes). When both happen at the same time, the preview/test widget (testWidget) and the saved widget can get out of sync, causing the overlay to alternate between old and new text.

* make app auto shutdown after 10 secs of confirmation dialog being open and no response

* Edit AdvancedHttpClient - 'AdvancedHttpClient.PatchAsync(string, HttpContent)' hides inherited member 'HttpClient.PatchAsync(string?, HttpContent?)'. Use the new keyword if hiding was intended.

* update duelgamecommandmodel.cs

The result of the expression is always 'true' since a value of type 'CancellationToken' is never equal to 'null' of type 'CancellationToken?'

* update wordscramble game command model - CancellationToken is a struct in .NET 8, can't be null.

The result of the expression is always 'true' since a value of type 'CancellationToken' is never equal to 'null' of type 'CancellationToken?'

* update ttsmonsterservice  - 'WebClient.WebClient()' is obsolete: 'WebRequest, HttpWebRequest, ServicePoint, and WebClient are obsolete. Use HttpClient instead.'

* streamloots service - update media stream to use new httpclient and removed obselete webrequest code

* Update base, reporter, and wpf projects to .net9. Update all MSFT libraries to v9+ and sqlite library to v3

* Added comment about blurry image in ImageHelper.cs

* added Timeout = Timeout.InfiniteTimeSpan to streamloots service so it doesnt timeout

* fix cancellationtoken for streamloots

* update csproj to target x64 and self contained

* remove unused packages

* update packages

* update csproj files, removed unused packages, updated packages that wont break the app

* refactor: simplify window styles in LoginWindow and MainWindow

* Revert "refactor: simplify window styles in LoginWindow and MainWindow"

This reverts commit 66ad85eb6e9c6011bc95bf8e57a12066abafa9f9.

* remove obsolete servicepointmanager from app.xaml.cs

* initial update to material design 3

* update to materialdesign3 sliders

* Remove old MD2 references

* Update license agreement, new user wizard, login window, and update window to MD3 style

* Update MixItUp oAuth logo to new static api link

* adjust elevation for login card

* update mix it up logo

* keep mainwindow at default size

* update user data import window to MD3

* Update User Data editor window to MD3

* remove old references from userdataeditor page

* Updates Quotes data import to MD3

* MD3 overlay tabs in overlay editor and overlay endpoint editor

* md3'd dashboard window

* simple updates for currency,lnventory, redemptionstore, and streampass windows

* update community commands upload window

* update command editor window

* update game command editor window

* update controls and remove old resources

* update chatlist control

* fix alignment in developerapi service control

* fix alignment in discord service control

* fix alignment in donordrive service control

* adjust service container and remove old resources

* fix vertical alignment in generic toggle control for settings page

* overhaul of settings controls, vertical alignment for all settings controls and update combo box/text blocks to use outlined styles

* remove "Profile" from combo box @ login page

* vertical align usage requirement toggles

* game commands editors cleanup

* lower width between checkboxes in chat overlaywidget editor

* Adjust webhooks page controls

* increase width for twitch channel points actions control

* increase width for action controls in twitch bits page

* increase actions width for trovo spells control

* increase width for actions column in timer page

* increase actions width for streamloots card control

* remove old MD2 resources references

* fix service control crash

* CRASHING EXCEPTION:
System.Windows.ResourceReferenceKeyNotFoundException: 'PrimaryHueLightBrush' resource not found.
   at MS.Internal.Helper.FindResourceHelper.DoTryCatchWhen(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

* remove all old resources references

* moderation page improvement

* remove old resources from main menu

* update giveaway window control

* remove old references from games page

* adjust toggle width in games page

* remove old references from game queue

* update action control width in events page

* remove old references from currencyrankinventory control

* update CC action control to 250 width

* update communitycommand page

* update command history page remove old references

* update chat control and remove old references

* adjust width for chatcommandscontrol and remove old references

* update changelog control

* actiongroup update width

* update accounts control

* update about control

* fix cropped toggle in the chat action accordian

* reduce width in chat msg action and remove border

* change grid column width for conditional action

* VerticalAlignment="Center" for counter action

* change special identifier references to SpecialIdentifiers in chat msg action

* fix tabs in overlay action

* adjust width for timer overlay action control

* change width in SI action

* System.NotSupportedException: This type of CollectionView does not support changes to its SourceCollection from a thread different from the Dispatcher thread.
   at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at MixItUp.Base.Util.ListExtensions.ClearAndAddRange[T](Collection`1 list, IEnumerable`1 items) in C:\Users\admin\source\repos\mixitupapp\Desktop\MixItUp.Base\Util\ListExtensions.cs:line 150
   at MixItUp.Base.ViewModel.MainControls.RedemptionStoreMainControlViewModel.Refresh() in C:\Users\admin\source\repos\mixitupapp\Desktop\MixItUp.Base\ViewModel\MainControls\RedemptionStoreMainControlViewModel.cs:line 111
   at MixItUp.Base.ViewModel.MainControls.RedemptionStoreMainControlViewModel.RedemptionStorePurchaseModel_OnRedemptionStorePurchasesUpdated(Object sender, EventArgs e) in C:\Users\admin\source\repos\mixitupapp\Desktop\MixItUp.Base\ViewModel\MainControls\RedemptionStoreMainControlViewModel.cs:line 126
   at MixItUp.Base.Model.Currency.RedemptionStorePurchaseModel.RedemptionStorePurchasesUpdated() in C:\Users\admin\source\repos\mixitupapp\Desktop\MixItUp.Base\Model\Currency\RedemptionStoreProductModel.cs:line 92
   at MixItUp.Base.Model.Currency.RedemptionStorePurchaseModel.Redeem() in C:\Users\admin\source\repos\mixitupapp\Desktop\MixItUp.Base\Model\Currency\RedemptionStoreProductModel.cs:line 286
   at MixItUp.Base.Model.Currency.RedemptionStorePurchaseModel.Purchase(UserV2ViewModel user, IEnumerable`1 arguments) in C:\Users\admin\source\repos\mixitupapp\Desktop\MixItUp.Base\Model\Currency\RedemptionStoreProductModel.cs:line 150
   at MixItUp.Base.Services.ChatService.AddMessage(ChatMessageViewModel message) in C:\Users\admin\source\repos\mixitupapp\Desktop\MixItUp.Base\Services\ChatService.cs:line 742

* Added discord blurple icon

* added discord blurple icon reference to csproj

* added material design popup helper button for the login page

* added localized terms for PrivacyPolicy and TermsOfService for login page

* Auto localize TermsOfService & PrivacyPolicy

* testing advanced web request action with PUT, POST, and DELETE options added to action. todo: testing & localization

* use environment.processpath to start app when restoring backup

* localize web request action new UI text

* Added Counters API
GET    /api/v2/counters                      - Get all counters
GET    /api/v2/counters/{counterName}        - Get counter by name
POST   /api/v2/counters                      - Create counter | Body: {"Name": "deaths"}
POST   /api/v2/counters/{counterName}/set    - Set counter to value | Body: {"Amount": 42}
POST   /api/v2/counters/{counterName}/update - Increment/decrement counter | Body: {"Amount": 1}
POST   /api/v2/counters/{counterName}/reset  - Reset counter to default
DELETE /api/v2/counters/{counterName}        - Delete counter

* Use rfc7807 error msgs for api v2 routes

* add platform selector for chat page (All, Twitch, Trovo, YouTube)

* replace the platform text with logos

* remove hardcoded platforms and use streamingplatformtypenum.cs as a reference

* fix chatlistcontrol alignment for platform selector

* added platform selector to chat msg action

* Revert "added platform selector to chat msg action"

This reverts commit 9e2ee8a230cc01482d05afc2fef75b4b86141842.

* System.Windows.Data Error: 6 : 'TargetDefaultValueConverter' converter failed to convert value '' (type 'String'); fallback value will be used, if available. BindingExpression:Path=LogoPath; DataItem='PlatformOption' (HashCode=26977502); target element is 'Image' (Name=''); target property is 'Source' (type 'ImageSource') NotSupportedException:'System.NotSupportedException: ImageSourceConverter cannot convert from System.String.
   at MS.Internal.Data.DefaultValueConverter.ConvertHelper(Object o, Type destinationType, DependencyObject targetElement, CultureInfo culture, Boolean isForward)
   at MS.Internal.Data.TargetDefaultValueConverter.Convert(Object o, Type type, Object parameter, CultureInfo culture)
   at System.Windows.Data.BindingExpression.ConvertHelper(IValueConverter converter, Object value, Type targetType, Object parameter, CultureInfo culture)'

* increase minimized service groupbox height in services container

* YoutubeService add search by handle name (fixes add yt user in users page) with fallback to legacy username search

* Added dateto() and datefrom() to special identifier action

* Added theme service to make themes and colors change instantly

* clean and re-do theme service

* finalize theme service and fix combobox disabling

* Remove duplicate recent stream titles and games from channel page

* remove old httplistener naming

* improve currency responses and new models

* rename nocache to nocacheheadermiddleware

* update inventory responses

* added miu version as a header to dev api

* update miu signal r project to .net9

* remove transitive references from base proj

* remove  transitive references from wpf proj

* remove transitive reference from reporter proj

* bump packages to 9.0.10

* bump newtonsoft.json to 13.0.4

* from usewpf from base csproj and target net9.0 instead of net9.0-windows

* bump gong-wpf-dragdrop to version 4.0.0

---------

Co-authored-by: Verbatim_T (Tim) <6174906+verbatimt@users.noreply.github.com>