System.NotSupportedException: This type of CollectionView does not support changes to its SourceCollection from a thread different from the Dispatcher thread.    at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)    at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)    at MixItUp.Base.Util.ListExtensions.ClearAndAddRange[T](Collection`1 list, IEnumerable`1 items) in C:\Users\admin\source\repos\mixitupapp\Desktop\MixItUp.Base\Util\ListExtensions.cs:line 150    at MixItUp.Base.ViewModel.MainControls.RedemptionStoreMainControlViewModel.Refresh() in C:\Users\admin\source\repos\mixitupapp\Desktop\MixItUp.Base\ViewModel\MainControls\RedemptionStoreMainControlViewModel.cs:line 111    at MixItUp.Base.ViewModel.MainControls.RedemptionStoreMainControlViewModel.RedemptionStorePurchaseModel_OnRedemptionStorePurchasesUpdated(Object sender, EventArgs e) in C:\Users\admin\source\repos\mixitupapp\Desktop\MixItUp.Base\ViewModel\MainControls\RedemptionStoreMainControlViewModel.cs:line 126    at MixItUp.Base.Model.Currency.RedemptionStorePurchaseModel.RedemptionStorePurchasesUpdated() in C:\Users\admin\source\repos\mixitupapp\Desktop\MixItUp.Base\Model\Currency\RedemptionStoreProductModel.cs:line 92    at MixItUp.Base.Model.Currency.RedemptionStorePurchaseModel.Redeem() in C:\Users\admin\source\repos\mixitupapp\Desktop\MixItUp.Base\Model\Currency\RedemptionStoreProductModel.cs:line 286    at MixItUp.Base.Model.Currency.RedemptionStorePurchaseModel.Purchase(UserV2ViewModel user, IEnumerable`1 arguments) in C:\Users\admin\source\repos\mixitupapp\Desktop\MixItUp.Base\Model\Currency\RedemptionStoreProductModel.cs:line 150    at MixItUp.Base.Services.ChatService.AddMessage(ChatMessageViewModel message) in C:\Users\admin\source\repos\mixitupapp\Desktop\MixItUp.Base\Services\ChatService.cs:line 742